import { useAuth } from "@/_core/hooks/useAuth";
import { Archive, ArrowLeft, FolderOpen, LoaderCircle, Pencil, RotateCcw, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import { Link } from "wouter";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";

export default function ArchivedAlbums() {
  const { loading: authLoading, isAuthenticated } = useAuth({ redirectOnUnauthenticated: true });
  const albumsQuery = trpc.albums.listArchived.useQuery(undefined, { enabled: isAuthenticated });
  const [activeAlbumId, setActiveAlbumId] = useState<number | null>(null);
  const [nameDraft, setNameDraft] = useState("");
  const restore = trpc.albums.setArchived.useMutation({ onSuccess: () => { toast.success("Album dipulihkan ke rak aktif."); setActiveAlbumId(null); void albumsQuery.refetch(); }, onError: (error) => toast.error(error.message) });
  const rename = trpc.albums.rename.useMutation({ onSuccess: () => { toast.success("Nama album diperbarui."); void albumsQuery.refetch(); }, onError: (error) => toast.error(error.message) });
  const remove = trpc.albums.delete.useMutation({ onSuccess: () => { toast.success("Album dihapus. Frame asli tetap tersimpan."); setActiveAlbumId(null); void albumsQuery.refetch(); }, onError: (error) => toast.error(error.message) });
  const touch = trpc.albums.touch.useMutation();
  const albums = albumsQuery.data ?? [];
  const activeAlbum = albums.find((album) => album.id === activeAlbumId) ?? albums[0];
  useEffect(() => { if (activeAlbum) { setNameDraft(activeAlbum.name); touch.mutate({ albumId: activeAlbum.id }); } }, [activeAlbum?.id]);
  if (authLoading || !isAuthenticated || albumsQuery.isLoading) return <main className="settings-loading proof-loading"><span className="aperture-mark" /><LoaderCircle className="spin-icon" size={24} /> Membuka album terarsip...</main>;
  if (albumsQuery.isError) return <main className="settings-loading"><strong>Album terarsip belum dapat dimuat.</strong><button className="secondary-action" onClick={() => void albumsQuery.refetch()}>Muat ulang</button></main>;
  return <main className="archived-page"><header className="settings-header"><Link href="/profil"><ArrowLeft size={16} /> Kembali ke profil</Link><div className="profile-wordmark"><span className="aperture-mark" /><strong>Lensa Saku</strong><small>ALBUM TERARSIP</small></div></header><section className="archived-hero"><span className="eyebrow">RAK PRIVAT / 05</span><h1>Album yang<br /><em>disimpan dulu.</em></h1><p>Pengarsipan menyembunyikan album dari rak utama, namun tidak menghapus frame ataupun riwayatnya. Buka album untuk memperbarui jejak aksesnya, pulihkan saat diperlukan, atau hapus pengelompokannya secara permanen.</p></section><section className="archived-manager">{albums.length ? <><div className="archived-list">{albums.map((album) => <button key={album.id} className={activeAlbum?.id === album.id ? "is-active" : ""} onClick={() => setActiveAlbumId(album.id)}>{album.coverUrl ? <img src={album.coverUrl} alt="" /> : <Archive size={21} />}<span><strong>{album.name}</strong><small>{album.itemCount} frame · Diarsipkan {new Intl.DateTimeFormat("id-ID", { dateStyle: "medium" }).format(new Date(album.archivedAt ?? album.updatedAt))}</small></span></button>)}</div>{activeAlbum && <article className="archived-detail"><div className="archived-detail-heading"><div><span className="eyebrow">ALBUM TERPILIH</span><h2>{activeAlbum.name}</h2><p>{activeAlbum.itemCount} frame tetap berada di dalam album ini.</p></div><button onClick={() => restore.mutate({ albumId: activeAlbum.id, isArchived: false })} disabled={restore.isPending}><RotateCcw size={15} /> Pulihkan album</button></div><form onSubmit={(event) => { event.preventDefault(); if (nameDraft.trim() && nameDraft.trim() !== activeAlbum.name) rename.mutate({ albumId: activeAlbum.id, name: nameDraft.trim() }); }}><input aria-label="Nama album terarsip" value={nameDraft} maxLength={80} onChange={(event) => setNameDraft(event.target.value)} /><button disabled={rename.isPending}><Pencil size={14} /> Simpan nama</button><button type="button" className="archived-delete" disabled={remove.isPending} onClick={() => { if (window.confirm(`Hapus album “${activeAlbum.name}”? Frame asli tidak akan dihapus.`)) remove.mutate({ albumId: activeAlbum.id }); }}><Trash2 size={14} /> Hapus album</button></form><div className="archived-frame-grid">{activeAlbum.items.length ? activeAlbum.items.map((item) => <article key={item.transformId}><img src={item.resultUrl ?? ""} alt={item.title} /><strong>{item.title}</strong><small>{item.style} · {item.aspectRatio}</small></article>) : <p>Album ini belum memiliki frame.</p>}</div></article>}</> : <div className="archived-empty"><FolderOpen size={28} /><strong>Belum ada album terarsip.</strong><p>Album yang kamu arsipkan dari profil akan muncul di sini tanpa menghapus frame di dalamnya.</p><Link href="/profil">Kembali ke profil</Link></div>}</section></main>;
}
