import { useAuth } from "@/_core/hooks/useAuth";
import { useBrand } from "@/contexts/BrandContext";
import { trpc } from "@/lib/trpc";
import { isTemporaryTrpcTransportError } from "@/lib/trpcRecovery";
import { ArrowRight, CheckCircle2, CircleAlert, Eye, EyeOff, KeyRound, LockKeyhole, Mail, Send, UserRound } from "lucide-react";
import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { Link, useLocation } from "wouter";
import { toast } from "sonner";

function safeDestination(value: string | null) { return value && value.startsWith("/") && !value.startsWith("//") ? value : "/"; }

function PasswordField({ id, value, onChange, placeholder = "Minimal 12 karakter", label = "Kata sandi" }: { id: string; value: string; onChange: (value: string) => void; placeholder?: string; label?: string }) {
  const [visible, setVisible] = useState(false);
  return <label className="auth-field" htmlFor={id}><span>{label}</span><div className="auth-input-wrap"><LockKeyhole size={17} /><input id={id} autoComplete={id === "register-password" ? "new-password" : "current-password"} type={visible ? "text" : "password"} value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} required minLength={12} maxLength={128} /><button type="button" className="auth-eye" onClick={() => setVisible(!visible)} aria-label={visible ? "Sembunyikan kata sandi" : "Tampilkan kata sandi"}>{visible ? <EyeOff size={17} /> : <Eye size={17} />}</button></div></label>;
}

function AuthApiRetry({ error, onRetry, pending }: { error: unknown; onRetry: () => Promise<void>; pending: boolean }) {
  if (!isTemporaryTrpcTransportError(error)) return null;
  return <aside className="auth-api-retry" role="status" data-testid="auth-api-retry"><CircleAlert size={16} /><div><strong>Koneksi sementara terganggu.</strong><p>Server sedang menyegarkan. Data akun belum diubah.</p></div><button type="button" data-testid="auth-api-retry-button" disabled={pending} onClick={() => void onRetry()}>{pending ? "Mencoba…" : "Coba lagi"}</button></aside>;
}

export default function Auth() {
  const [, navigate] = useLocation(); const { brand } = useBrand(); const { user, loading, isAuthenticated, error: authError, refresh } = useAuth(); const utils = trpc.useUtils(); const [location] = useLocation(); const isRegister = location === "/daftar"; const next = useMemo(() => safeDestination(new URLSearchParams(window.location.search).get("next")), []);
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [retryingApi, setRetryingApi] = useState(false);
  useEffect(() => { if (!loading && isAuthenticated) navigate(user?.mustChangePassword ? "/ganti-kata-sandi" : user?.emailVerifiedAt ? next : "/verifikasi-email", { replace: true }); }, [isAuthenticated, loading, navigate, next, user?.emailVerifiedAt, user?.mustChangePassword]);
  const finish = async (result: { user: NonNullable<typeof user> }) => { utils.auth.me.setData(undefined, result.user); await utils.auth.me.invalidate(); navigate(result.user.mustChangePassword ? "/ganti-kata-sandi" : result.user.emailVerifiedAt ? next : "/verifikasi-email", { replace: true }); };
  const login = trpc.auth.login.useMutation({ onSuccess: (value) => void finish(value), onError: (error) => toast.error(error.message) }); const register = trpc.auth.register.useMutation({ onSuccess: (value) => void finish(value), onError: (error) => toast.error(error.message) }); const pending = login.isPending || register.isPending;
  const retryApi = async () => { setRetryingApi(true); try { await Promise.all([refresh(), utils.brand.get.invalidate()]); } finally { setRetryingApi(false); } };
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (isRegister) register.mutate({ name, email, password }); else login.mutate({ email, password }); }
  return <main className="auth-page"><section className="auth-poster"><Link href="/" className="auth-brand"><img src={brand.iconUrl} alt="Ikon Lensa Saku" /><span><strong>Lensa Saku</strong><small>STUDIO AI</small></span></Link><div className="auth-poster-copy"><span className="eyebrow">ruang privat untuk visualmu</span><h1>Masuk ke<br /><em>kamar gelap</em> digital.</h1><p>Simpan proses, hasil, dan arah kreatifmu dalam akun yang hanya milikmu.</p></div><div className="auth-poster-foot"><span>01</span><i /><small>FOTO MASUK · ARAH JELAS · HASIL TERSIMPAN</small></div></section><section className="auth-form-side"><div className="auth-card"><Link href="/" className="auth-back">← Kembali ke studio</Link><div className="auth-kicker"><span>{isRegister ? "AKUN BARU" : "AKUN PRIBADI"}</span><i /></div><h2>{isRegister ? "Buat akunmu." : "Selamat datang kembali."}</h2><p>{isRegister ? "Daftar dengan email untuk membuat galeri visual yang benar-benar privat. Kami akan mengirim tautan verifikasi sebelum studio dibuka." : "Masuk dengan email dan kata sandi akun Lensa Saku."}</p><AuthApiRetry error={authError} onRetry={retryApi} pending={retryingApi} /><form onSubmit={submit} className="auth-form">{isRegister && <label className="auth-field" htmlFor="register-name"><span>Nama</span><div className="auth-input-wrap"><UserRound size={17} /><input id="register-name" autoComplete="name" value={name} onChange={(event) => setName(event.target.value)} placeholder="Nama yang ingin ditampilkan" required minLength={2} maxLength={80} /></div></label>}<label className="auth-field" htmlFor="auth-email"><span>Email</span><div className="auth-input-wrap"><Mail size={17} /><input id="auth-email" autoComplete="email" type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="nama@email.com" required maxLength={320} /></div></label><PasswordField id={isRegister ? "register-password" : "login-password"} value={password} onChange={setPassword} />{isRegister && <small className="auth-hint"><CheckCircle2 size={14} /> Gunakan sedikitnya 12 karakter untuk menjaga koleksimu.</small>}<button className="auth-submit" disabled={pending || retryingApi}>{pending ? "Memproses…" : isRegister ? "Buat akun & lanjutkan" : "Masuk ke studio"}<ArrowRight size={17} /></button></form>{!isRegister && <Link className="auth-text-link" href="/lupa-kata-sandi">Lupa kata sandi?</Link>}<div className="auth-switch"><span>{isRegister ? "Sudah punya akun?" : "Belum punya akun?"}</span><Link href={`${isRegister ? "/masuk" : "/daftar"}?next=${encodeURIComponent(next)}`}>{isRegister ? "Masuk" : "Buat akun"}</Link></div><p className="auth-privacy"><KeyRound size={14} /> Tidak terhubung dengan akun Manus atau layanan sosial mana pun.</p></div></section></main>;
}

function AccountUtilityShell({ kicker, title, description, children }: { kicker: string; title: string; description: string; children: React.ReactNode }) { const { brand } = useBrand(); return <main className="auth-page auth-change"><section className="auth-card"><img className="auth-change-icon" src={brand.iconUrl} alt="Ikon Lensa Saku" /><span className="auth-alert">{kicker}</span><h1>{title}</h1><p>{description}</p>{children}</section></main>; }

export function ForgotPassword() { const [email, setEmail] = useState(""); const [sent, setSent] = useState(false); const mutation = trpc.auth.requestPasswordReset.useMutation({ onSuccess: () => setSent(true), onError: (error) => toast.error(error.message) }); if (sent) return <AccountUtilityShell kicker="EMAIL TERKIRIM" title="Periksa kotak masukmu." description="Jika alamat tersebut terdaftar, kami telah mengirim tautan untuk mengatur ulang kata sandi. Tautan berlaku selama 20 menit."><Link className="auth-text-link" href="/masuk">Kembali ke masuk</Link></AccountUtilityShell>; return <AccountUtilityShell kicker="PULIHKAN AKUN" title="Lupa kata sandi?" description="Masukkan alamat email akunmu. Kami akan mengirim tautan aman untuk membuat kata sandi baru."><form className="auth-form" onSubmit={(event) => { event.preventDefault(); mutation.mutate({ email }); }}><label className="auth-field" htmlFor="forgot-email"><span>Email</span><div className="auth-input-wrap"><Mail size={17} /><input id="forgot-email" autoComplete="email" type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="nama@email.com" required maxLength={320} /></div></label><button className="auth-submit" disabled={mutation.isPending}>{mutation.isPending ? "Mengirim…" : "Kirim tautan reset"}<Send size={17} /></button></form><Link className="auth-text-link" href="/masuk">Kembali ke masuk</Link></AccountUtilityShell>; }

export function ResetPassword() { const [, navigate] = useLocation(); const token = useMemo(() => new URLSearchParams(window.location.search).get("token") ?? "", []); const [password, setPassword] = useState(""); const mutation = trpc.auth.resetPassword.useMutation({ onSuccess: () => { toast.success("Kata sandi baru sudah tersimpan. Silakan masuk."); navigate("/masuk", { replace: true }); }, onError: (error) => toast.error(error.message) }); if (!token) return <AccountUtilityShell kicker="TAUTAN TIDAK LENGKAP" title="Reset tidak tersedia." description="Gunakan tautan lengkap yang dikirimkan melalui email."><Link className="auth-text-link" href="/lupa-kata-sandi">Minta tautan baru</Link></AccountUtilityShell>; return <AccountUtilityShell kicker="KATA SANDI BARU" title="Amankan akunmu." description="Buat kata sandi baru dengan sedikitnya 12 karakter. Tautan ini hanya dapat digunakan sekali."><form className="auth-form" onSubmit={(event) => { event.preventDefault(); mutation.mutate({ token, password }); }}><PasswordField id="reset-password" label="Kata sandi baru" value={password} onChange={setPassword} /><button className="auth-submit" disabled={mutation.isPending}>{mutation.isPending ? "Menyimpan…" : "Simpan kata sandi"}<ArrowRight size={17} /></button></form></AccountUtilityShell>; }

export function EmailVerification() { const [, navigate] = useLocation(); const { user, loading, isAuthenticated } = useAuth(); const utils = trpc.useUtils(); const token = useMemo(() => new URLSearchParams(window.location.search).get("token") ?? "", []); const started = useRef(false); const [verified, setVerified] = useState(false); const verify = trpc.auth.verifyEmail.useMutation({ onSuccess: async (value) => { utils.auth.me.setData(undefined, value.user); await utils.auth.me.invalidate(); setVerified(true); }, onError: (error) => toast.error(error.message) }); const resend = trpc.auth.resendVerification.useMutation({ onSuccess: (value) => { if (value.sent) toast.success("Email verifikasi telah dikirim."); else if (value.alreadyVerified) toast.success("Email akun ini sudah terverifikasi."); }, onError: (error) => toast.error(error.message) }); useEffect(() => { if (token && !started.current) { started.current = true; verify.mutate({ token }); } }, [token, verify]); if (verified) return <AccountUtilityShell kicker="EMAIL TERVERIFIKASI" title="Studio sudah terbuka." description="Alamat emailmu telah terkonfirmasi. Sekarang kamu dapat memakai seluruh fitur privat Lensa Saku."><button className="auth-submit" onClick={() => navigate(isAuthenticated ? "/" : "/masuk", { replace: true })}>{isAuthenticated ? "Buka studio" : "Masuk ke studio"} <ArrowRight size={17} /></button></AccountUtilityShell>; if (token) return <AccountUtilityShell kicker="MEMVERIFIKASI" title="Memeriksa tautanmu." description={verify.isPending ? "Tunggu sebentar, kami sedang memverifikasi alamat email." : "Tautan verifikasi tidak dapat digunakan. Minta email baru setelah masuk."}><Link className="auth-text-link" href="/masuk">Kembali ke masuk</Link></AccountUtilityShell>; if (loading) return <main className="auth-page auth-loading">Menyiapkan verifikasi…</main>; if (!isAuthenticated || !user) return <AccountUtilityShell kicker="VERIFIKASI EMAIL" title="Masuk terlebih dahulu." description="Masuk ke akunmu untuk meminta ulang tautan verifikasi email."><Link href="/masuk">Masuk</Link></AccountUtilityShell>; return <AccountUtilityShell kicker="VERIFIKASI EMAIL" title="Periksa kotak masukmu." description={`Kami memerlukan verifikasi untuk ${user.email ?? "alamat email akun ini"} sebelum studio dapat dipakai.`}><button className="auth-submit" onClick={() => resend.mutate()} disabled={resend.isPending}>{resend.isPending ? "Mengirim…" : "Kirim ulang verifikasi"}<Send size={17} /></button><p className="auth-privacy"><CircleAlert size={14} /> Periksa folder spam bila email belum terlihat. Email baru hanya dapat dikirim sekali per menit.</p></AccountUtilityShell>; }

export function ChangePassword() { const [, navigate] = useLocation(); const { brand } = useBrand(); const { user, loading } = useAuth({ redirectOnUnauthenticated: true }); const utils = trpc.useUtils(); const [currentPassword, setCurrentPassword] = useState(""); const [nextPassword, setNextPassword] = useState(""); const mutation = trpc.auth.changePassword.useMutation({ onSuccess: async (value) => { utils.auth.me.setData(undefined, value.user); await utils.auth.me.invalidate(); toast.success("Kata sandi baru sudah tersimpan."); navigate("/", { replace: true }); }, onError: (error) => toast.error(error.message) }); if (loading || !user) return <main className="auth-page auth-loading">Menyiapkan akun…</main>; return <main className="auth-page auth-change"><section className="auth-card"><img className="auth-change-icon" src={brand.iconUrl} alt="Ikon Lensa Saku" /><span className="auth-alert">PENGAMANAN AKUN</span><h1>Ganti kata sandi sementara.</h1><p>Akun administrator ini menggunakan kata sandi awal. Buat kata sandi baru sebelum membuka studio.</p><form className="auth-form" onSubmit={(event) => { event.preventDefault(); mutation.mutate({ currentPassword, nextPassword }); }}><PasswordField id="current-password" label="Kata sandi sementara" value={currentPassword} onChange={setCurrentPassword} placeholder="Masukkan kata sandi awal" /><PasswordField id="next-password" label="Kata sandi baru" value={nextPassword} onChange={setNextPassword} placeholder="Minimal 12 karakter" /><button className="auth-submit" disabled={mutation.isPending}>{mutation.isPending ? "Menyimpan…" : "Simpan & lanjutkan"}<ArrowRight size={17} /></button></form></section></main>; }
