import { useAuth } from "@/_core/hooks/useAuth";
import { MediaImage } from "@/components/MediaImage";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, Download, Images, LoaderCircle } from "lucide-react";
import { Link } from "wouter";

export default function CollaborationHistory() {
  const { loading, isAuthenticated } = useAuth({ redirectOnUnauthenticated: true }); const projects = trpc.photo.collaborationProjects.useQuery(undefined, { enabled: isAuthenticated });
  if (loading || !isAuthenticated) return <main className="collaboration-loading"><LoaderCircle className="spin-icon" size={24} /> Membuka riwayat kolaborasi…</main>;
  return <main className="collaboration-history-page"><header className="collaboration-header"><Link href="/kolaborasi"><ArrowLeft size={16} /> Kembali ke kolaborasi</Link><span><Images size={17} /> Lensa Saku / riwayat</span><Link href="/profil">Koleksi privat</Link></header><section className="collaboration-history-hero"><span className="eyebrow">ARSIP PRIVAT / KOLABORASI</span><h1>Proyek yang<br /><em>pernah disatukan.</em></h1><p>Riwayat ini hanya menampilkan proyek Kolaborasi Foto milikmu. Hasil dapat diunduh kembali tanpa mengekspos sumber kepada pengguna lain.</p></section><section className="collaboration-history-grid">{projects.isLoading ? <div className="collaboration-history-empty"><LoaderCircle className="spin-icon" size={22} /> Memuat proyek…</div> : projects.data?.length ? projects.data.map((project) => <article key={project.id}><div className="collaboration-history-image">{project.resultUrl ? <MediaImage src={project.resultUrl} alt={project.title} /> : <span>{project.status.toUpperCase()}</span>}</div><div><span>{(project.template || "free").toUpperCase()} · {project.aspectRatio}</span><h2>{project.title}</h2><p>{new Intl.DateTimeFormat("id-ID", { dateStyle: "medium", timeStyle: "short" }).format(new Date(project.createdAt))} · {project.status === "completed" ? "Selesai" : project.status === "failed" ? "Gagal" : "Diproses"}</p>{project.resultUrl && <a href={project.resultUrl} download><Download size={14} /> Unduh hasil</a>}</div></article>) : <div className="collaboration-history-empty"><Images size={26} /><strong>Belum ada proyek kolaborasi.</strong><p>Mulai dari dua foto privat, pilih template, dan proyekmu akan muncul di sini setelah dibuat.</p><Link href="/kolaborasi">Buka Kolaborasi Foto</Link></div>}</section></main>;
}
