/**
 * Kamar Gelap Editorial: each prompt directs a transformation while preserving
 * the uploaded subject, product, labels, and documented scene.
 */
export const recipeIds = ["headshot", "beauty", "portrait_window", "family", "graduation", "personal_brand", "couple_portrait", "team_portrait", "background", "product", "product_white", "marketplace", "flatlay", "cosmetic", "jewelry", "handmade", "apparel_product", "furniture_product", "automotive", "food", "beverage", "bakery", "food_moody", "dessert", "coffee", "street_food", "social", "reels_cover", "creator_frame", "thumbnail_clean", "personal_story", "fashion", "lookbook", "accessory", "shoe_detail", "interior", "light", "listing", "workspace", "hotel_room", "storefront", "exterior", "restore", "detail", "old_color", "scan_clean", "portrait_restore", "low_light_recover", "document", "receipt_clean", "menu_clean", "ramadan_iftar", "ramadan_hampers", "lebaran_family", "lebaran_promo", "lebaran_product", "travel", "night", "sketch", "film_analog", "duotone", "color_pop", "comic_ink"] as const;
export const aspectRatioIds = ["1:1", "16:9", "9:16"] as const;
export const styleIds = ["editorial", "realistic", "anime", "cinematic", "vintage", "pastel", "minimal", "monochrome", "neon", "watercolor", "clean", "luxury", "soft_light", "vibrant", "matte"] as const;

export type RecipeId = (typeof recipeIds)[number];
export type AspectRatioId = (typeof aspectRatioIds)[number];
export type StyleId = (typeof styleIds)[number];

export const photoRecipes: Record<RecipeId, { title: string; prompt: string }> = {
  headshot: { title: "Headshot rapi", prompt: "Transform this into a polished professional editorial headshot. Preserve the person's exact identity, facial features, age, skin tone, hairstyle, pose, and clothing. Use soft sculpted studio lighting, a warm ivory or muted charcoal background, clean natural color, realistic skin texture, and premium Indonesian business editorial photography. Do not add text, logos, extra people, distorted anatomy, or artificial beauty-filter skin." },
  beauty: { title: "Retouch natural", prompt: "Refine this portrait with a natural editorial retouch. Preserve the person's exact identity, age, facial structure, skin tone, hairstyle, expression, pose, and clothing. Balance uneven light, reduce temporary distractions subtly, retain real skin texture, and keep an honest human appearance. Do not add text, logos, artificial skin, extra people, altered facial features, changed body shape, or altered anatomy." },
  portrait_window: { title: "Potret cahaya jendela", prompt: "Transform this portrait into an intimate window-light editorial photograph. Preserve the person's exact identity, age, face, skin tone, hairstyle, expression, pose, clothing, and framing. Use believable soft side light, gentle shadow rolloff, realistic skin texture, and warm natural color. Do not add text, logos, extra people, altered facial features, changed body shape, or artificial skin." },
  family: { title: "Potret keluarga", prompt: "Transform this family photograph into a warm, refined family editorial portrait. Preserve every person's exact identity, age, relationship, facial features, body proportions, clothing, pose, count, and relative positions. Use natural balanced light and a calm timeless color treatment. Do not add text, logos, extra people, remove people, alter faces, alter anatomy, or invent objects." },
  graduation: { title: "Wisuda berkelas", prompt: "Transform this graduation photograph into a polished celebratory editorial portrait. Preserve the graduate's exact identity, face, age, outfit, cap, gown, accessories, diploma details, pose, companions, and setting. Use refined flattering light, dignified color, and realistic fabric texture. Do not add text, logos, extra people, change credentials, alter facial features, or invent awards." },
  personal_brand: { title: "Profil personal brand", prompt: "Transform this portrait into a confident, approachable personal-brand editorial image. Preserve the person's exact identity, facial features, age, skin tone, hairstyle, expression, body proportions, clothing, pose, and existing tools. Use clean directional light, an authentic professional setting, and calm negative space for later optional copy. Do not add text, logos, extra people, altered facial features, altered body shape, or invented credentials." },
  couple_portrait: { title: "Potret pasangan elegan", prompt: "Transform this existing two-person portrait into a warm, refined paired editorial photograph. Preserve each person's exact identity, age, facial features, skin tone, clothing, pose, count, relative position, and all documented relationship context without inferring or changing it. Use gentle balanced light and a timeless natural finish. Do not add text, logos, people, remove people, alter faces, alter anatomy, change clothing, or invent intimacy." },
  team_portrait: { title: "Potret tim profesional", prompt: "Transform this existing team or group photograph into a polished professional editorial portrait. Preserve every person's exact identity, age, face, clothing, body proportions, pose, count, and relative position. Use even credible light, balanced color, and a clean workplace or studio atmosphere. Do not add text, logos, people, remove people, alter faces, alter anatomy, uniforms, roles, or invent branding." },
  background: { title: "Latar studio bersih", prompt: "Create a clean premium studio-background version of this image. Preserve the exact main person or product, identity, pose, object shape, labels, colors, clothing, and framing. Replace only distracting surroundings with a believable warm ivory, soft gray, or charcoal editorial studio background and natural grounded shadow. Do not add text, logos, extra objects, people, duplicate products, or altered labels." },
  product: { title: "Produk katalog", prompt: "Transform this into a refined commercial product catalog photograph. Preserve the product's exact shape, materials, labels, colors, dimensions, and branding. Use a warm ivory studio surface, soft directional light, controlled charcoal shadow, premium editorial styling, and a clean composition with generous negative space. Do not add text, new labels, logos, people, duplicate products, or invented product features." },
  product_white: { title: "Produk latar putih", prompt: "Transform this product image into a precise clean-background commerce photograph. Preserve the exact product shape, proportions, materials, colors, package, labels, branding, included items, and quantities. Use a seamless believable white or pale-neutral background with soft grounded shadows and even accurate light. Do not add text, new labels, logos, people, products, props, duplicate items, or invented features." },
  marketplace: { title: "Marketplace cerah", prompt: "Transform this product image into a clear, bright marketplace-ready photograph. Preserve the exact product shape, size, materials, colors, packaging, labels, brand marks, and included items. Use even believable daylight, an uncluttered neutral background, crisp focus, and a practical centered composition. Do not add text, new labels, logos, people, products, props, or invented features." },
  flatlay: { title: "Flat lay terarah", prompt: "Transform this top-down product photograph into a refined editorial flat lay. Preserve every existing product, object, label, color, quantity, orientation, and readable detail. Improve only spacing, surface light, shadow control, and visual hierarchy while retaining the documented arrangement. Do not add text, logos, hands, products, props, duplicate objects, or changed labels." },
  cosmetic: { title: "Kosmetik bersih", prompt: "Transform this cosmetics photograph into a premium clean beauty campaign image. Preserve the exact packaging, product shapes, shades, caps, labels, brand marks, quantities, and materials. Use soft diffused studio light, clean surfaces, realistic highlights, and restrained editorial color. Do not add text, new labels, people, extra products, altered packaging, or invented claims." },
  jewelry: { title: "Detail perhiasan", prompt: "Transform this jewelry or accessory photograph into a precise luxury detail image. Preserve the exact item design, gemstones, metal color, engravings, clasps, proportions, labels, and quantity. Use believable controlled sparkle, soft reflected light, sharp material texture, and an elegant neutral setting. Do not add text, logos, extra jewelry, altered stones, invented engravings, or people." },
  handmade: { title: "Produk buatan tangan", prompt: "Transform this handmade or craft product photograph into a tactile artisan commerce image. Preserve the exact object shape, materials, colors, textures, construction marks, labels, quantities, and scale. Use honest directional light and a quiet surface that reveals workmanship faithfully. Do not add text, logos, people, products, props, altered labels, or invented details." },
  apparel_product: { title: "Pakaian untuk katalog", prompt: "Transform this apparel product photograph into a clear premium fashion-commerce image. Preserve the exact garment design, fabric, color, seams, pattern, fit, accessories, tags, labels, size cues, and all visible details. Use even controlled light and a restrained clean backdrop. Do not add text, logos, people, altered garments, extra clothing, altered labels, or invented styling details." },
  furniture_product: { title: "Furnitur terarah", prompt: "Transform this furniture product photograph into a refined home-commerce editorial image. Preserve the exact furniture form, dimensions, material, upholstery, finish, hardware, color, setting, and quantity. Use natural believable interior light, clean perspective, and true texture. Do not add text, logos, people, furniture, decor, altered materials, or impossible architecture." },
  automotive: { title: "Otomotif detail", prompt: "Transform this vehicle or automotive-detail photograph into a precise premium editorial image. Preserve the exact vehicle model, paint color, body shape, wheels, lights, badges, plates, accessories, condition, and setting. Use realistic reflections and controlled directional light. Do not add text, logos, people, vehicles, altered badges, license details, or invented modifications." },
  food: { title: "Menu menggoda", prompt: "Transform this food photograph into a premium modern restaurant campaign image. Preserve the dish, ingredients, plating, tableware, and serving size faithfully. Enhance natural appetite appeal with warm window light, rich but realistic color, refined charcoal shadows, and a clear editorial composition. Do not add text, logos, hands, extra dishes, impossible ingredients, or plastic-looking food." },
  beverage: { title: "Minuman segar", prompt: "Transform this beverage photograph into a fresh premium drinks campaign image. Preserve the exact drink, glass, garnish, ice, liquid level, color, label, tableware, and serving size. Use believable condensation, controlled natural highlights, and a clean refreshing composition. Do not add text, logos, extra glasses, ingredients, hands, impossible splashes, or altered labels." },
  bakery: { title: "Roti & pastry", prompt: "Transform this bakery photograph into a warm artisanal pastry editorial image. Preserve the exact baked goods, shapes, fillings, toppings, plates, utensils, quantity, and serving size. Use cozy directional light, realistic golden texture, and refined food styling without changing ingredients. Do not add text, logos, hands, extra pastries, impossible toppings, or plastic-looking food." },
  food_moody: { title: "Menu moody", prompt: "Transform this food photograph into a sophisticated moody restaurant editorial image. Preserve the exact dish, ingredients, plating, tableware, serving size, and composition. Use believable low-key directional light, deep controlled shadows, and rich realistic color while retaining appetizing natural texture. Do not add text, logos, hands, extra dishes, ingredients, or invented garnish." },
  dessert: { title: "Dessert & manis", prompt: "Transform this dessert photograph into a refined pastry-and-dessert campaign image. Preserve the exact dessert, layers, toppings, glaze, garnish, plate, utensil, quantity, serving size, and composition. Use soft appetizing light, truthful texture, and controlled highlights. Do not add text, logos, hands, dishes, desserts, toppings, ingredients, or invented garnish." },
  coffee: { title: "Kopi & kafe", prompt: "Transform this coffee or cafe beverage photograph into a calm premium cafe editorial image. Preserve the exact cup, glass, drink, foam, ice, liquid level, garnish, label, tableware, and serving size. Use believable window light and tactile natural materials. Do not add text, logos, hands, extra drinks, food, ingredients, impossible foam art, or altered labels." },
  street_food: { title: "Jajanan lokal", prompt: "Transform this existing street-food photograph into a vivid yet honest local-food editorial image. Preserve the exact food, ingredients, serving ware, seller setup, signage, people, quantities, labels, and documented atmosphere. Improve only light, color balance, and focal clarity. Do not add text, logos, people, dishes, ingredients, props, remove visible items, or invent cultural details." },
  social: { title: "Konten sosial", prompt: "Transform this into a clean, high-impact social media editorial image. Preserve the central subject, identity, objects, and composition faithfully. Use lively but natural color, crisp contrast, warm paper-like light, and a premium creative-studio finish with uncluttered negative space. Do not add text, captions, logos, extra limbs, extra people, or unrelated objects." },
  reels_cover: { title: "Cover video vertikal", prompt: "Transform this into a clear vertical social-video cover image. Preserve the exact main subject, identity, objects, colors, clothing, and composition. Use a strong mobile-safe focal point, polished contrast, and intentional negative space that remains empty for optional later copy. Do not add text, captions, logos, extra people, limbs, objects, or unrelated scenery." },
  creator_frame: { title: "Frame kreator", prompt: "Transform this creator-content photograph into a polished personal-studio frame. Preserve the exact person, identity, pose, clothing, tools, products, background objects, and composition. Use warm natural light, clear focal separation, and authentic practical texture. Do not add text, captions, logos, extra people, hands, equipment, or invented products." },
  thumbnail_clean: { title: "Cover konten bersih", prompt: "Transform this existing image into a high-clarity content-cover visual with a strong mobile-safe focal point. Preserve the exact person, identity, objects, clothing, setting, composition, and empty areas. Use polished contrast and intentional clear negative space for optional later copy. Do not add text, captions, logos, people, limbs, objects, or unrelated scenery." },
  personal_story: { title: "Cerita personal", prompt: "Transform this personal lifestyle photograph into an intimate, authentic visual-story editorial image. Preserve the exact person, identity, age, clothing, objects, setting, moment, and composition. Use natural emotional light and restrained color that remains truthful to the documented scene. Do not add text, logos, people, altered faces, altered anatomy, objects, or invented story details." },
  fashion: { title: "Kampanye fashion", prompt: "Transform this into a refined fashion campaign photograph. Preserve the person's exact identity, body proportions, outfit, accessories, pose, and skin tone. Use intentional editorial styling, a controlled studio or architectural setting, premium garment texture, and a confident full-length or half-length composition. Do not add text, logos, altered garment design, duplicate limbs, or unrelated people." },
  lookbook: { title: "Lookbook bersih", prompt: "Transform this fashion photograph into a clean commercial lookbook image. Preserve the exact model identity, body proportions, outfit, accessories, garment construction, colors, pose, and visible product details. Use even premium light, a simple believable backdrop, and crisp material texture. Do not add text, logos, altered clothing, extra garments, people, limbs, or accessories." },
  accessory: { title: "Aksesori terfokus", prompt: "Transform this fashion accessory photograph into a refined product-detail editorial image. Preserve the exact bag, shoe, watch, scarf, or accessory design, color, materials, hardware, branding, size, and placement. Use controlled light and clean focus to show texture faithfully. Do not add text, logos, people, extra accessories, altered hardware, or invented details." },
  shoe_detail: { title: "Sepatu & detail", prompt: "Transform this shoe or footwear photograph into a crisp fashion-detail editorial image. Preserve the exact shoe design, material, color, sole, laces, stitching, logo, pair count, wear condition, and placement. Use believable directional light with clear texture and scale. Do not add text, logos, people, footwear, altered materials, extra pairs, or invented details." },
  interior: { title: "Ruang & properti", prompt: "Transform this interior or property image into a bright architectural editorial photograph. Preserve the room layout, dimensions, furniture, materials, fixtures, windows, and perspective faithfully. Use balanced daylight, straight vertical lines, realistic textures, and a calm premium magazine finish. Do not add text, rooms, furniture, people, or impossible architectural features." },
  light: { title: "Cahaya seimbang", prompt: "Correct and enhance the exposure of this photograph with balanced natural light. Preserve the exact subject, identity, objects, colors, composition, material detail, and atmosphere. Recover believable highlight and shadow detail, neutralize unwanted color casts, and create a clean premium editorial finish. Do not add text, logos, people, objects, invented details, or change the documented time of day." },
  listing: { title: "Listing properti", prompt: "Transform this property photograph into a clear, inviting real-estate listing image. Preserve the exact room layout, dimensions, furniture, fixtures, materials, windows, views, and perspective. Use realistic balanced daylight, straight verticals, and clean natural color while keeping all documented features intact. Do not add text, rooms, furniture, people, decor, views, or impossible architectural details." },
  workspace: { title: "Meja kerja rapi", prompt: "Transform this workspace photograph into a refined productive editorial image. Preserve the exact desk, tools, devices, documents, products, cables, furniture, labels, and room layout. Improve only natural light, color balance, surface clarity, and visual order without removing important objects. Do not add text, logos, people, devices, props, or invent details not present in the source." },
  hotel_room: { title: "Kamar hotel terang", prompt: "Transform this existing hotel or accommodation room photograph into a calm hospitality editorial image. Preserve the exact room layout, furniture, fixtures, linens, materials, windows, views, amenities, and perspective. Use balanced believable daylight and straight vertical lines. Do not add text, logos, rooms, furniture, people, decor, amenities, or impossible architectural details." },
  storefront: { title: "Etalase toko rapi", prompt: "Transform this storefront or retail display photograph into a clear inviting business editorial image. Preserve the exact facade, signs, products, shelves, labels, layout, colors, people, and documented surroundings. Improve only natural light, perspective, and visual clarity. Do not add text, logos, products, people, signs, prices, or invented claims." },
  exterior: { title: "Eksterior arsitektur", prompt: "Transform this building exterior photograph into a refined architectural editorial image. Preserve the exact building form, facade, materials, windows, entrance, landscaping, weather, people, vehicles, and perspective. Use believable natural light, corrected vertical lines, and accurate material texture. Do not add text, logos, buildings, people, vehicles, landscaping, or impossible structures." },
  restore: { title: "Pulihkan foto", prompt: "Restore and enhance this photograph. Preserve its exact subject, identity, composition, and historical character. Carefully reduce scratches, haze, color casts, and softness while retaining authentic texture and believable detail. Do not add text, missing people, logos, clothing, objects, or facial features that were not visible." },
  detail: { title: "Detail lebih tajam", prompt: "Enhance this photograph with carefully improved clarity, texture, and perceived detail. Preserve its exact subject, identity, composition, labels, colors, and original character. Reduce mild blur and noise naturally, retain realistic grain where appropriate, and avoid over-sharpened edges. Do not add text, missing objects, faces, logos, features, or altered readable labels." },
  old_color: { title: "Pulih warna lama", prompt: "Restore the color balance of this older photograph. Preserve its exact people, identity, clothing, objects, composition, historical mood, and original character. Correct only believable fading, casts, and mild unevenness while retaining authentic grain and age. Do not add text, people, clothing, objects, facial features, modern colors, or invented detail." },
  scan_clean: { title: "Hasil pindai bersih", prompt: "Clean and refine this scanned photograph or paper image. Preserve the exact visible subject, handwritten marks, printed content, colors, crop, composition, and material character. Reduce only dust, scanning shadows, mild skew, and non-content noise without fabricating hidden content. Do not add text, logos, people, objects, handwriting, missing details, or altered readable content." },
  portrait_restore: { title: "Potret lama dipulihkan", prompt: "Restore this older portrait carefully. Preserve the person's exact visible identity, age cues, facial features, hairstyle, clothing, pose, crop, background, and historical character. Reduce only scratches, haze, fading, and mild softness while keeping authentic texture. Do not add text, people, facial features, clothing, objects, modern styling, or invented detail." },
  low_light_recover: { title: "Pulihkan foto gelap", prompt: "Recover this underexposed or low-light photograph with realistic light and detail. Preserve the exact subject, identity, objects, colors, composition, atmosphere, and documented time of day. Recover believable shadows and highlights without erasing the intended mood. Do not add text, logos, people, objects, daylight, artificial scenery, or invented detail." },
  document: { title: "Dokumen terbaca", prompt: "Refine this document or paper photograph for legibility and clean perspective. Preserve every existing word, number, signature, stamp, handwritten mark, layout, page edge, and visible object exactly as captured. Improve only even lighting, contrast, mild perspective, and non-content shadows. Do not add text, remove text, change text, logos, stamps, signatures, people, or invented document content." },
  receipt_clean: { title: "Struk & kuitansi jelas", prompt: "Refine this receipt, invoice, or proof-of-payment photograph for legibility. Preserve every existing word, number, currency symbol, date, signature, stamp, handwritten mark, layout, page edge, and visible object exactly as captured. Improve only lighting, contrast, mild perspective, and non-content shadows. Do not add text, remove text, change text, prices, logos, stamps, signatures, or invented document content." },
  menu_clean: { title: "Menu & daftar rapi", prompt: "Refine this menu, list, or printed information photograph for clear faithful reading. Preserve every existing word, number, price, symbol, handwriting mark, layout, page edge, color, and visible object exactly as captured. Improve only lighting, contrast, mild perspective, and non-content noise. Do not add text, remove text, change text, prices, logos, items, signatures, or invented document content." },
  ramadan_iftar: { title: "Menu berbuka hangat", prompt: "Transform this existing iftar or Ramadan food photograph into a warm, refined seasonal restaurant editorial image. Preserve the exact dish, ingredients, plating, tableware, serving size, labels, and composition. Use believable golden evening light, subtle celebration atmosphere, and appetizing natural texture without inventing cultural props. Do not add text, logos, hands, people, dishes, ingredients, dates, lanterns, or altered food." },
  ramadan_hampers: { title: "Hampers Ramadan", prompt: "Transform this Ramadan hamper photograph into a polished seasonal retail image. Preserve the exact boxes, packaging, products, labels, brand marks, ribbons, colors, quantities, and included items. Use warm premium light and restrained celebratory texture while keeping a clean area for optional later copy. Do not add text, logos, products, people, gift items, altered labels, or invented claims." },
  lebaran_family: { title: "Momen Lebaran keluarga", prompt: "Transform this Lebaran family photograph into a warm, timeless family celebration portrait. Preserve every person's exact identity, age, face, clothing, pose, body proportions, count, relative positions, and setting. Use natural flattering light and refined festive color while keeping the moment authentic. Do not add text, logos, people, remove people, alter faces, alter anatomy, gifts, or invented celebration details." },
  lebaran_promo: { title: "Promo Lebaran toko", prompt: "Transform this existing store product photograph into a polished Lebaran retail campaign image. Preserve the exact products, packaging, labels, colors, quantities, store setting, and composition. Use elegant warm celebration styling and intentional empty space for optional later promotional copy. Do not add text, prices, discount claims, logos, people, products, altered labels, or invented offers." },
  lebaran_product: { title: "Produk hadiah Lebaran", prompt: "Transform this Lebaran gift product photograph into a refined premium gifting editorial image. Preserve the exact package design, products, materials, colors, labels, quantities, and visible details. Use tasteful celebratory light and a clean elegant composition without altering the merchandise. Do not add text, logos, products, people, gift contents, altered labels, or invented brand claims." },
  travel: { title: "Perjalanan berkesan", prompt: "Transform this travel or outdoor photograph into a refined destination editorial image. Preserve the exact people, landmarks, landscape, weather cues, architecture, objects, and original composition. Use balanced natural atmosphere, clear depth, elegant color, and believable local light. Do not add text, landmarks, people, logos, impossible scenery, or change the documented location." },
  night: { title: "Malam sinematik", prompt: "Transform this image into a cinematic night editorial photograph. Preserve the main subject, identity, objects, and original composition. Use realistic low-light exposure, rich but controlled shadows, practical ambient light, and refined color contrast. Do not add text, logos, extra people, duplicated objects, or fantasy elements." },
  sketch: { title: "Sketsa editorial", prompt: "Transform this into an original editorial sketch illustration. Preserve the exact main subject, identity, pose, objects, composition, and readable labels. Use refined hand-drawn linework, restrained paper texture, and a contemporary original visual language. Do not add text, logos, people, objects, altered anatomy, unrelated scenery, or imitate a named artist or studio." },
  film_analog: { title: "Film analog hangat", prompt: "Transform this photograph with a tasteful warm analog-film print character. Preserve the exact subject, identity, objects, colors that carry meaning, composition, readable labels, and original atmosphere. Use restrained grain, natural highlight rolloff, and believable print texture without degrading important detail. Do not add text, logos, people, objects, scratches, light leaks, or altered content." },
  duotone: { title: "Grafis dua warna", prompt: "Transform this into an original contemporary two-tone graphic image. Preserve the exact main subject, identity, pose, object forms, composition, and readable labels. Use limited harmonious color planes, strong faithful silhouettes, and a clean print-like finish while retaining recognizable source detail. Do not add text, captions, logos, extra people, objects, altered anatomy, or imitate a named artist." },
  color_pop: { title: "Warna pop modern", prompt: "Transform this into an original contemporary color-pop editorial image. Preserve the exact main subject, identity, pose, objects, clothing, labels, and composition. Use lively yet controlled color contrast, clean tonal separation, and a polished modern finish. Do not add text, captions, logos, people, objects, altered anatomy, or unrelated scenery." },
  comic_ink: { title: "Ilustrasi tinta modern", prompt: "Transform this into an original contemporary ink-and-color illustration. Preserve the exact main subject, identity, pose, object forms, composition, and readable labels. Use expressive ink linework, restrained color blocks, and a unique original visual language. Do not add text, captions, logos, people, objects, altered anatomy, or imitate a named artist or studio." },
};

const aspectDirections: Record<AspectRatioId, string> = {
  "1:1": "Compose the final image in a balanced 1:1 square format, with the important subject fully visible and comfortable edge space.",
  "16:9": "Compose the final image in a cinematic 16:9 horizontal format, maintaining the important subject fully in frame with considered editorial negative space.",
  "9:16": "Compose the final image in a vertical 9:16 format for mobile social stories, keeping the important subject fully visible through the central safe area.",
};

const styleDirections: Record<StyleId, string> = {
  editorial: "Use a refined warm editorial-photo finish with controlled natural color and tactile film-like depth.",
  realistic: "Use faithful photorealism with natural texture, physically plausible light, accurate material detail, and no illustrative simplification.",
  anime: "Use an original polished anime illustration with clean linework, expressive yet faithful proportions, cinematic cel shading, and an original visual language. Do not imitate a named artist or studio.",
  cinematic: "Use a cinematic photo grade with deliberate contrast, deep dimensional shadows, graceful highlights, and filmic color separation while retaining photorealism.",
  vintage: "Use a tasteful analog print character with restrained grain, faded warm tones, tactile paper texture, and believable archival color without damaging the subject.",
  pastel: "Use a soft pastel color treatment with airy light, gentle contrast, and clean contemporary commercial styling while preserving natural detail.",
  minimal: "Use a minimal high-key art direction with uncluttered negative space, restrained color, clear subject separation, and a polished commercial finish.",
  monochrome: "Use a high-contrast black-and-white editorial treatment with nuanced grayscale, preserved texture, and no artificial color accents.",
  neon: "Use a controlled contemporary neon-night color grade with physically plausible practical light, clean contrast, and retained photorealism.",
  watercolor: "Use an original contemporary watercolor illustration with faithful forms, transparent pigment texture, and no imitation of a named artist.",
  clean: "Use a clean commercial-photo finish with neutral color, balanced contrast, precise edge clarity, and restrained natural texture.",
  luxury: "Use a refined luxury-editorial finish with controlled highlights, tactile material detail, elegant tonal depth, and retained photorealism.",
  soft_light: "Use soft diffused daylight with gentle shadow transitions, calm contrast, and faithful natural texture.",
  vibrant: "Use vivid but believable color, clear tonal separation, and energetic natural light without oversaturation or altered product colors.",
  matte: "Use a restrained matte print finish with softened highlights, rich midtones, subtle grain, and preserved critical detail.",
};

export function buildTransformPrompt(recipeId: RecipeId, aspectRatio: AspectRatioId = "1:1", style: StyleId = "editorial", customInstruction?: string) {
  const instruction = customInstruction?.trim().replace(/[\u0000-\u001F]+/g, " ").slice(0, 360);
  const direction = instruction ? `Optional user direction, apply only when compatible with the preservation rules: ${instruction}` : "";
  const guard = "Non-negotiable: preserve the original main subject, identity, composition, and readable labels. Do not add text, logos, extra people, duplicate objects, or unrelated details.";
  return `${photoRecipes[recipeId].prompt} ${styleDirections[style]} ${aspectDirections[aspectRatio]} ${direction} ${guard}`.trim();
}
