/**
 * Kamar Gelap Editorial: each prompt directs a transformation while preserving
 * the uploaded subject, product, labels, and documented scene.
 */
export const recipeIds = ["headshot", "beauty", "portrait_window", "family", "graduation", "background", "product", "marketplace", "flatlay", "cosmetic", "jewelry", "food", "beverage", "bakery", "food_moody", "social", "reels_cover", "creator_frame", "fashion", "lookbook", "accessory", "interior", "light", "listing", "workspace", "restore", "detail", "old_color", "scan_clean", "document", "ramadan_iftar", "ramadan_hampers", "lebaran_family", "lebaran_promo", "lebaran_product", "travel", "night", "sketch", "film_analog", "duotone"] as const;
export const aspectRatioIds = ["1:1", "16:9", "9:16"] as const;
export const styleIds = ["editorial", "realistic", "anime", "cinematic", "vintage", "pastel", "minimal", "monochrome", "neon", "watercolor"] as const;

export type RecipeId = (typeof recipeIds)[number];
export type AspectRatioId = (typeof aspectRatioIds)[number];
export type StyleId = (typeof styleIds)[number];

export const photoRecipes: Record<RecipeId, { title: string; prompt: string }> = {
  headshot: { title: "Headshot rapi", prompt: "Transform this into a polished professional editorial headshot. Preserve the person's exact identity, facial features, age, skin tone, hairstyle, pose, and clothing. Use soft sculpted studio lighting, a warm ivory or muted charcoal background, clean natural color, realistic skin texture, and premium Indonesian business editorial photography. Do not add text, logos, extra people, distorted anatomy, or artificial beauty-filter skin." },
  beauty: { title: "Retouch natural", prompt: "Refine this portrait with a natural editorial retouch. Preserve the person's exact identity, age, facial structure, skin tone, hairstyle, expression, pose, and clothing. Balance uneven light, reduce temporary distractions subtly, retain real skin texture, and keep an honest human appearance. Do not add text, logos, artificial skin, extra people, altered facial features, changed body shape, or altered anatomy." },
  portrait_window: { title: "Potret cahaya jendela", prompt: "Transform this portrait into an intimate window-light editorial photograph. Preserve the person's exact identity, age, face, skin tone, hairstyle, expression, pose, clothing, and framing. Use believable soft side light, gentle shadow rolloff, realistic skin texture, and warm natural color. Do not add text, logos, extra people, altered facial features, changed body shape, or artificial skin." },
  family: { title: "Potret keluarga", prompt: "Transform this family photograph into a warm, refined family editorial portrait. Preserve every person's exact identity, age, relationship, facial features, body proportions, clothing, pose, count, and relative positions. Use natural balanced light and a calm timeless color treatment. Do not add text, logos, extra people, remove people, alter faces, alter anatomy, or invent objects." },
  graduation: { title: "Wisuda berkelas", prompt: "Transform this graduation photograph into a polished celebratory editorial portrait. Preserve the graduate's exact identity, face, age, outfit, cap, gown, accessories, diploma details, pose, companions, and setting. Use refined flattering light, dignified color, and realistic fabric texture. Do not add text, logos, extra people, change credentials, alter facial features, or invent awards." },
  background: { title: "Latar studio bersih", prompt: "Create a clean premium studio-background version of this image. Preserve the exact main person or product, identity, pose, object shape, labels, colors, clothing, and framing. Replace only distracting surroundings with a believable warm ivory, soft gray, or charcoal editorial studio background and natural grounded shadow. Do not add text, logos, extra objects, people, duplicate products, or altered labels." },
  product: { title: "Produk katalog", prompt: "Transform this into a refined commercial product catalog photograph. Preserve the product's exact shape, materials, labels, colors, dimensions, and branding. Use a warm ivory studio surface, soft directional light, controlled charcoal shadow, premium editorial styling, and a clean composition with generous negative space. Do not add text, new labels, logos, people, duplicate products, or invented product features." },
  marketplace: { title: "Marketplace cerah", prompt: "Transform this product image into a clear, bright marketplace-ready photograph. Preserve the exact product shape, size, materials, colors, packaging, labels, brand marks, and included items. Use even believable daylight, an uncluttered neutral background, crisp focus, and a practical centered composition. Do not add text, new labels, logos, people, products, props, or invented features." },
  flatlay: { title: "Flat lay terarah", prompt: "Transform this top-down product photograph into a refined editorial flat lay. Preserve every existing product, object, label, color, quantity, orientation, and readable detail. Improve only spacing, surface light, shadow control, and visual hierarchy while retaining the documented arrangement. Do not add text, logos, hands, products, props, duplicate objects, or changed labels." },
  cosmetic: { title: "Kosmetik bersih", prompt: "Transform this cosmetics photograph into a premium clean beauty campaign image. Preserve the exact packaging, product shapes, shades, caps, labels, brand marks, quantities, and materials. Use soft diffused studio light, clean surfaces, realistic highlights, and restrained editorial color. Do not add text, new labels, people, extra products, altered packaging, or invented claims." },
  jewelry: { title: "Detail perhiasan", prompt: "Transform this jewelry or accessory photograph into a precise luxury detail image. Preserve the exact item design, gemstones, metal color, engravings, clasps, proportions, labels, and quantity. Use believable controlled sparkle, soft reflected light, sharp material texture, and an elegant neutral setting. Do not add text, logos, extra jewelry, altered stones, invented engravings, or people." },
  food: { title: "Menu menggoda", prompt: "Transform this food photograph into a premium modern restaurant campaign image. Preserve the dish, ingredients, plating, tableware, and serving size faithfully. Enhance natural appetite appeal with warm window light, rich but realistic color, refined charcoal shadows, and a clear editorial composition. Do not add text, logos, hands, extra dishes, impossible ingredients, or plastic-looking food." },
  beverage: { title: "Minuman segar", prompt: "Transform this beverage photograph into a fresh premium drinks campaign image. Preserve the exact drink, glass, garnish, ice, liquid level, color, label, tableware, and serving size. Use believable condensation, controlled natural highlights, and a clean refreshing composition. Do not add text, logos, extra glasses, ingredients, hands, impossible splashes, or altered labels." },
  bakery: { title: "Roti & pastry", prompt: "Transform this bakery photograph into a warm artisanal pastry editorial image. Preserve the exact baked goods, shapes, fillings, toppings, plates, utensils, quantity, and serving size. Use cozy directional light, realistic golden texture, and refined food styling without changing ingredients. Do not add text, logos, hands, extra pastries, impossible toppings, or plastic-looking food." },
  food_moody: { title: "Menu moody", prompt: "Transform this food photograph into a sophisticated moody restaurant editorial image. Preserve the exact dish, ingredients, plating, tableware, serving size, and composition. Use believable low-key directional light, deep controlled shadows, and rich realistic color while retaining appetizing natural texture. Do not add text, logos, hands, extra dishes, ingredients, or invented garnish." },
  social: { title: "Konten sosial", prompt: "Transform this into a clean, high-impact social media editorial image. Preserve the central subject, identity, objects, and composition faithfully. Use lively but natural color, crisp contrast, warm paper-like light, and a premium creative-studio finish with uncluttered negative space. Do not add text, captions, logos, extra limbs, extra people, or unrelated objects." },
  reels_cover: { title: "Cover video vertikal", prompt: "Transform this into a clear vertical social-video cover image. Preserve the exact main subject, identity, objects, colors, clothing, and composition. Use a strong mobile-safe focal point, polished contrast, and intentional negative space that remains empty for optional later copy. Do not add text, captions, logos, extra people, limbs, objects, or unrelated scenery." },
  creator_frame: { title: "Frame kreator", prompt: "Transform this creator-content photograph into a polished personal-studio frame. Preserve the exact person, identity, pose, clothing, tools, products, background objects, and composition. Use warm natural light, clear focal separation, and authentic practical texture. Do not add text, captions, logos, extra people, hands, equipment, or invented products." },
  fashion: { title: "Kampanye fashion", prompt: "Transform this into a refined fashion campaign photograph. Preserve the person's exact identity, body proportions, outfit, accessories, pose, and skin tone. Use intentional editorial styling, a controlled studio or architectural setting, premium garment texture, and a confident full-length or half-length composition. Do not add text, logos, altered garment design, duplicate limbs, or unrelated people." },
  lookbook: { title: "Lookbook bersih", prompt: "Transform this fashion photograph into a clean commercial lookbook image. Preserve the exact model identity, body proportions, outfit, accessories, garment construction, colors, pose, and visible product details. Use even premium light, a simple believable backdrop, and crisp material texture. Do not add text, logos, altered clothing, extra garments, people, limbs, or accessories." },
  accessory: { title: "Aksesori terfokus", prompt: "Transform this fashion accessory photograph into a refined product-detail editorial image. Preserve the exact bag, shoe, watch, scarf, or accessory design, color, materials, hardware, branding, size, and placement. Use controlled light and clean focus to show texture faithfully. Do not add text, logos, people, extra accessories, altered hardware, or invented details." },
  interior: { title: "Ruang & properti", prompt: "Transform this interior or property image into a bright architectural editorial photograph. Preserve the room layout, dimensions, furniture, materials, fixtures, windows, and perspective faithfully. Use balanced daylight, straight vertical lines, realistic textures, and a calm premium magazine finish. Do not add text, rooms, furniture, people, or impossible architectural features." },
  light: { title: "Cahaya seimbang", prompt: "Correct and enhance the exposure of this photograph with balanced natural light. Preserve the exact subject, identity, objects, colors, composition, material detail, and atmosphere. Recover believable highlight and shadow detail, neutralize unwanted color casts, and create a clean premium editorial finish. Do not add text, logos, people, objects, invented details, or change the documented time of day." },
  listing: { title: "Listing properti", prompt: "Transform this property photograph into a clear, inviting real-estate listing image. Preserve the exact room layout, dimensions, furniture, fixtures, materials, windows, views, and perspective. Use realistic balanced daylight, straight verticals, and clean natural color while keeping all documented features intact. Do not add text, rooms, furniture, people, decor, views, or impossible architectural details." },
  workspace: { title: "Meja kerja rapi", prompt: "Transform this workspace photograph into a refined productive editorial image. Preserve the exact desk, tools, devices, documents, products, cables, furniture, labels, and room layout. Improve only natural light, color balance, surface clarity, and visual order without removing important objects. Do not add text, logos, people, devices, props, or invent details not present in the source." },
  restore: { title: "Pulihkan foto", prompt: "Restore and enhance this photograph. Preserve its exact subject, identity, composition, and historical character. Carefully reduce scratches, haze, color casts, and softness while retaining authentic texture and believable detail. Do not add text, missing people, logos, clothing, objects, or facial features that were not visible." },
  detail: { title: "Detail lebih tajam", prompt: "Enhance this photograph with carefully improved clarity, texture, and perceived detail. Preserve its exact subject, identity, composition, labels, colors, and original character. Reduce mild blur and noise naturally, retain realistic grain where appropriate, and avoid over-sharpened edges. Do not add text, missing objects, faces, logos, features, or altered readable labels." },
  old_color: { title: "Pulih warna lama", prompt: "Restore the color balance of this older photograph. Preserve its exact people, identity, clothing, objects, composition, historical mood, and original character. Correct only believable fading, casts, and mild unevenness while retaining authentic grain and age. Do not add text, people, clothing, objects, facial features, modern colors, or invented detail." },
  scan_clean: { title: "Hasil pindai bersih", prompt: "Clean and refine this scanned photograph or paper image. Preserve the exact visible subject, handwritten marks, printed content, colors, crop, composition, and material character. Reduce only dust, scanning shadows, mild skew, and non-content noise without fabricating hidden content. Do not add text, logos, people, objects, handwriting, missing details, or altered readable content." },
  document: { title: "Dokumen terbaca", prompt: "Refine this document or paper photograph for legibility and clean perspective. Preserve every existing word, number, signature, stamp, handwritten mark, layout, page edge, and visible object exactly as captured. Improve only even lighting, contrast, mild perspective, and non-content shadows. Do not add text, remove text, change text, logos, stamps, signatures, people, or invented document content." },
  ramadan_iftar: { title: "Menu berbuka hangat", prompt: "Transform this existing iftar or Ramadan food photograph into a warm, refined seasonal restaurant editorial image. Preserve the exact dish, ingredients, plating, tableware, serving size, labels, and composition. Use believable golden evening light, subtle celebration atmosphere, and appetizing natural texture without inventing cultural props. Do not add text, logos, hands, people, dishes, ingredients, dates, lanterns, or altered food." },
  ramadan_hampers: { title: "Hampers Ramadan", prompt: "Transform this Ramadan hamper photograph into a polished seasonal retail image. Preserve the exact boxes, packaging, products, labels, brand marks, ribbons, colors, quantities, and included items. Use warm premium light and restrained celebratory texture while keeping a clean area for optional later copy. Do not add text, logos, products, people, gift items, altered labels, or invented claims." },
  lebaran_family: { title: "Momen Lebaran keluarga", prompt: "Transform this Lebaran family photograph into a warm, timeless family celebration portrait. Preserve every person's exact identity, age, face, clothing, pose, body proportions, count, relative positions, and setting. Use natural flattering light and refined festive color while keeping the moment authentic. Do not add text, logos, people, remove people, alter faces, alter anatomy, gifts, or invented celebration details." },
  lebaran_promo: { title: "Promo Lebaran toko", prompt: "Transform this existing store product photograph into a polished Lebaran retail campaign image. Preserve the exact products, packaging, labels, colors, quantities, store setting, and composition. Use elegant warm celebration styling and intentional empty space for optional later promotional copy. Do not add text, prices, discount claims, logos, people, products, altered labels, or invented offers." },
  lebaran_product: { title: "Produk hadiah Lebaran", prompt: "Transform this Lebaran gift product photograph into a refined premium gifting editorial image. Preserve the exact package design, products, materials, colors, labels, quantities, and visible details. Use tasteful celebratory light and a clean elegant composition without altering the merchandise. Do not add text, logos, products, people, gift contents, altered labels, or invented brand claims." },
  travel: { title: "Perjalanan berkesan", prompt: "Transform this travel or outdoor photograph into a refined destination editorial image. Preserve the exact people, landmarks, landscape, weather cues, architecture, objects, and original composition. Use balanced natural atmosphere, clear depth, elegant color, and believable local light. Do not add text, landmarks, people, logos, impossible scenery, or change the documented location." },
  night: { title: "Malam sinematik", prompt: "Transform this image into a cinematic night editorial photograph. Preserve the main subject, identity, objects, and original composition. Use realistic low-light exposure, rich but controlled shadows, practical ambient light, and refined color contrast. Do not add text, logos, extra people, duplicated objects, or fantasy elements." },
  sketch: { title: "Sketsa editorial", prompt: "Transform this into an original editorial sketch illustration. Preserve the exact main subject, identity, pose, objects, composition, and readable labels. Use refined hand-drawn linework, restrained paper texture, and a contemporary original visual language. Do not add text, logos, people, objects, altered anatomy, unrelated scenery, or imitate a named artist or studio." },
  film_analog: { title: "Film analog hangat", prompt: "Transform this photograph with a tasteful warm analog-film print character. Preserve the exact subject, identity, objects, colors that carry meaning, composition, readable labels, and original atmosphere. Use restrained grain, natural highlight rolloff, and believable print texture without degrading important detail. Do not add text, logos, people, objects, scratches, light leaks, or altered content." },
  duotone: { title: "Grafis dua warna", prompt: "Transform this into an original contemporary two-tone graphic image. Preserve the exact main subject, identity, pose, object forms, composition, and readable labels. Use limited harmonious color planes, strong faithful silhouettes, and a clean print-like finish while retaining recognizable source detail. Do not add text, captions, logos, extra people, objects, altered anatomy, or imitate a named artist." },
};

const aspectDirections: Record<AspectRatioId, string> = {
  "1:1": "Compose the final image in a balanced 1:1 square format, with the important subject fully visible and comfortable edge space.",
  "16:9": "Compose the final image in a cinematic 16:9 horizontal format, maintaining the important subject fully in frame with considered editorial negative space.",
  "9:16": "Compose the final image in a vertical 9:16 format for mobile social stories, keeping the important subject fully visible through the central safe area.",
};

const styleDirections: Record<StyleId, string> = {
  editorial: "Use a refined warm editorial-photo finish with controlled natural color and tactile film-like depth.",
  realistic: "Use faithful photorealism with natural texture, physically plausible light, accurate material detail, and no illustrative simplification.",
  anime: "Use an original polished anime illustration with clean linework, expressive yet faithful proportions, cinematic cel shading, and an original visual language. Do not imitate a named artist or studio.",
  cinematic: "Use a cinematic photo grade with deliberate contrast, deep dimensional shadows, graceful highlights, and filmic color separation while retaining photorealism.",
  vintage: "Use a tasteful analog print character with restrained grain, faded warm tones, tactile paper texture, and believable archival color without damaging the subject.",
  pastel: "Use a soft pastel color treatment with airy light, gentle contrast, and clean contemporary commercial styling while preserving natural detail.",
  minimal: "Use a minimal high-key art direction with uncluttered negative space, restrained color, clear subject separation, and a polished commercial finish.",
  monochrome: "Use a high-contrast black-and-white editorial treatment with nuanced grayscale, preserved texture, and no artificial color accents.",
  neon: "Use a controlled contemporary neon-night color grade with physically plausible practical light, clean contrast, and retained photorealism.",
  watercolor: "Use an original contemporary watercolor illustration with faithful forms, transparent pigment texture, and no imitation of a named artist.",
};

export function buildTransformPrompt(recipeId: RecipeId, aspectRatio: AspectRatioId = "1:1", style: StyleId = "editorial", customInstruction?: string) {
  const instruction = customInstruction?.trim().replace(/[\u0000-\u001F]+/g, " ").slice(0, 360);
  const direction = instruction ? `Optional user direction, apply only when compatible with the preservation rules: ${instruction}` : "";
  const guard = "Non-negotiable: preserve the original main subject, identity, composition, and readable labels. Do not add text, logos, extra people, duplicate objects, or unrelated details.";
  return `${photoRecipes[recipeId].prompt} ${styleDirections[style]} ${aspectDirections[aspectRatio]} ${direction} ${guard}`.trim();
}
