import { Move, RotateCcw, SlidersHorizontal } from "lucide-react";
import { useRef } from "react";
import { CollaborationLayoutPresetControls } from "./CollaborationLayoutPresetControls";

export type CollaborationLayout = { firstX: number; firstY: number; firstScale: number; secondX: number; secondY: number; secondScale: number };
export const defaultCollaborationLayout: CollaborationLayout = { firstX: 0, firstY: 0, firstScale: 1, secondX: 0, secondY: 0, secondScale: 1 };

export function CollaborationLayoutPreview({ firstUrl, secondUrl, template, layout, onChange }: { firstUrl?: string; secondUrl?: string; template: string; layout: CollaborationLayout; onChange: (next: CollaborationLayout) => void }) {
  const drag = useRef<{ side: "first" | "second"; startX: number; startY: number; baseX: number; baseY: number } | null>(null);
  const move = (event: React.PointerEvent<HTMLDivElement>) => { const current = drag.current; if (!current) return; const box = event.currentTarget.getBoundingClientRect(); const x = Math.max(-80, Math.min(80, current.baseX + ((event.clientX - current.startX) / box.width) * 160)); const y = Math.max(-80, Math.min(80, current.baseY + ((event.clientY - current.startY) / box.height) * 160)); onChange(current.side === "first" ? { ...layout, firstX: Math.round(x), firstY: Math.round(y) } : { ...layout, secondX: Math.round(x), secondY: Math.round(y) }); };
  const start = (event: React.PointerEvent<HTMLDivElement>, side: "first" | "second") => { event.currentTarget.setPointerCapture(event.pointerId); drag.current = { side, startX: event.clientX, startY: event.clientY, baseX: side === "first" ? layout.firstX : layout.secondX, baseY: side === "first" ? layout.firstY : layout.secondY }; };
  return <section className={`interactive-layout-preview template-${template}`} aria-labelledby="layout-preview-title"><div className="layout-preview-heading"><div><span className="eyebrow">PRATINJAU LAYOUT / 03</span><h2 id="layout-preview-title">Atur ruang dua foto.</h2><p>Tarik masing-masing frame atau gunakan kontrol proporsi. Ini panduan privat; AI dapat menyesuaikan detail akhir.</p></div><button type="button" onClick={() => onChange(defaultCollaborationLayout)}><RotateCcw size={14} /> Reset</button></div><div className="layout-stage" onPointerMove={move} onPointerUp={() => { drag.current = null; }} onPointerCancel={() => { drag.current = null; }}><div className="layout-object first" onPointerDown={(event) => start(event, "first")} style={{ transform: `translate(${layout.firstX}%, ${layout.firstY}%) scale(${layout.firstScale})` }}>{firstUrl ? <img src={firstUrl} alt="Foto A pada pratinjau tata letak" /> : <span>FOTO A</span>}<i><Move size={13} /></i></div><div className="layout-object second" onPointerDown={(event) => start(event, "second")} style={{ transform: `translate(${layout.secondX}%, ${layout.secondY}%) scale(${layout.secondScale})` }}>{secondUrl ? <img src={secondUrl} alt="Foto B pada pratinjau tata letak" /> : <span>FOTO B</span>}<i><Move size={13} /></i></div></div><div className="layout-adjustments"><label><SlidersHorizontal size={13} /> Foto A · proporsi <input type="range" min="60" max="140" value={Math.round(layout.firstScale * 100)} onChange={(event) => onChange({ ...layout, firstScale: Number(event.target.value) / 100 })} /></label><label><SlidersHorizontal size={13} /> Foto B · proporsi <input type="range" min="60" max="140" value={Math.round(layout.secondScale * 100)} onChange={(event) => onChange({ ...layout, secondScale: Number(event.target.value) / 100 })} /></label></div><CollaborationLayoutPresetControls layout={layout} onApply={onChange} /></section>;
}
