import { Copy, Link2, LoaderCircle, Trash2 } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";

export function CollaborationShareControls({ transformId }: { transformId: number }) {
  const utils = trpc.useUtils(); const links = trpc.photo.collaborationShareLinks.useQuery({ transformId }); const refresh = () => void utils.photo.collaborationShareLinks.invalidate({ transformId });
  const create = trpc.photo.createCollaborationShareLink.useMutation({ onSuccess: async (link) => { const url = `${window.location.origin}/bagikan/${link.token}`; try { await navigator.clipboard.writeText(url); toast.success("Tautan sementara dibuat dan disalin."); } catch { toast.success("Tautan sementara dibuat. Salin dari daftar di bawah."); } refresh(); }, onError: (error) => toast.error(error.message) }); const revoke = trpc.photo.revokeCollaborationShareLink.useMutation({ onSuccess: () => { refresh(); toast.success("Tautan berbagi dicabut."); }, onError: (error) => toast.error(error.message) });
  const copy = async (id: number) => { toast.message(`Tautan #${id} tidak dapat disalin ulang demi keamanan. Buat tautan baru bila diperlukan.`); };
  return <div className="collaboration-share-controls"><span><Link2 size={13} /> Tautan sementara</span><div className="share-create-buttons">{([1, 24, 72] as const).map((hours) => <button type="button" key={hours} disabled={create.isPending} onClick={() => create.mutate({ transformId, expiresInHours: hours })}>{create.isPending ? <LoaderCircle className="spin-icon" size={12} /> : null}{hours === 1 ? "1 jam" : `${hours / 24} hari`}</button>)}</div><small>Hanya hasil akhir dibagikan. Tautan dapat dicabut dan kedaluwarsa otomatis.</small>{links.data?.length ? <div className="share-link-list">{links.data.map((link) => <p key={link.id}><span>{link.revokedAt ? "DICABUT" : new Date(link.expiresAt) > new Date() ? `Aktif hingga ${new Date(link.expiresAt).toLocaleString("id-ID")}` : "KEDALUWARSA"}</span>{!link.revokedAt && new Date(link.expiresAt) > new Date() && <><button type="button" onClick={() => copy(link.id)} aria-label="Informasi tautan"><Copy size={12} /></button><button type="button" onClick={() => revoke.mutate({ shareLinkId: link.id })} aria-label="Cabut tautan"><Trash2 size={12} /></button></>}</p>)}</div> : null}</div>;
}
