import { Check, Pencil, Plus, RotateCcw } from "lucide-react";
import { useState } from "react";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";

type Background = "studio-ivory" | "soft-gray" | "charcoal" | "cafe" | "garden" | "office";
const options: { id: Background; label: string }[] = [{ id: "studio-ivory", label: "Studio ivory" }, { id: "soft-gray", label: "Studio abu lembut" }, { id: "charcoal", label: "Studio charcoal" }, { id: "cafe", label: "Kafe hangat" }, { id: "garden", label: "Taman natural" }, { id: "office", label: "Kantor minimal" }];
const emptyDraft = { name: "", background: "studio-ivory" as Background, isActive: true };

export function CollaborationBrandBackgroundPresets() {
  const utils = trpc.useUtils(); const [draft, setDraft] = useState(emptyDraft); const [editingId, setEditingId] = useState<number | null>(null);
  const presets = trpc.admin.collaborationBrandBackgroundPresets.useQuery();
  const refresh = () => { void utils.admin.collaborationBrandBackgroundPresets.invalidate(); };
  const create = trpc.admin.createCollaborationBrandBackgroundPreset.useMutation({ onSuccess: () => { refresh(); setDraft(emptyDraft); toast.success("Preset latar brand ditambahkan."); }, onError: (error) => toast.error(error.message) });
  const update = trpc.admin.updateCollaborationBrandBackgroundPreset.useMutation({ onSuccess: () => { refresh(); setDraft(emptyDraft); setEditingId(null); toast.success("Preset latar brand diperbarui."); }, onError: (error) => toast.error(error.message) });
  const save = () => { if (editingId) update.mutate({ id: editingId, ...draft }); else create.mutate(draft); };
  return <section className="collaboration-brand-background-manager"><header><div><span className="eyebrow">BRAND / KOLABORASI</span><h2>Preset latar brand.</h2><p>Hanya administrator dapat membuat, mengaktifkan, dan memakai preset ini saat menggabungkan dua foto. Preset tetap dibatasi agar hanya latar yang berubah.</p></div><span>{presets.data?.filter((item) => item.isActive).length ?? 0} aktif</span></header><div className="collaboration-brand-background-form"><label>Nama preset<input value={draft.name} maxLength={60} placeholder="Contoh: Ruang kerja brand" onChange={(event) => setDraft((value) => ({ ...value, name: event.target.value }))} /></label><label>Arah latar<select value={draft.background} onChange={(event) => setDraft((value) => ({ ...value, background: event.target.value as Background }))}>{options.map((option) => <option key={option.id} value={option.id}>{option.label}</option>)}</select></label><label className="collaboration-brand-background-active"><input type="checkbox" checked={draft.isActive} onChange={(event) => setDraft((value) => ({ ...value, isActive: event.target.checked }))} /> Aktifkan preset</label><div><button type="button" disabled={!draft.name.trim() || create.isPending || update.isPending} onClick={save}>{editingId ? <><Check size={14} /> Simpan perubahan</> : <><Plus size={14} /> Tambah preset latar</>}</button>{editingId && <button type="button" onClick={() => { setEditingId(null); setDraft(emptyDraft); }}><RotateCcw size={13} /> Batal</button>}</div></div><div className="collaboration-brand-background-list">{presets.isLoading ? <small>Memuat preset latar brand…</small> : presets.data?.length ? presets.data.map((preset) => <article key={preset.id} className={preset.isActive ? "is-active" : ""}><div><span>{preset.isActive ? "AKTIF" : "NONAKTIF"}</span><strong>{preset.name}</strong><p>{options.find((option) => option.id === preset.background)?.label}</p></div><button type="button" aria-label={`Sunting preset ${preset.name}`} onClick={() => { setEditingId(preset.id); setDraft({ name: preset.name, background: preset.background, isActive: preset.isActive }); }}><Pencil size={14} /> Sunting</button></article>) : <small>Belum ada preset latar brand.</small>}</div></section>;
}
