import { Copy, Link2, LoaderCircle, ShieldCheck, Trash2 } from "lucide-react";
import { useState } from "react";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";

export function CollaborationShareControls({ transformId }: { transformId: number }) {
  const utils = trpc.useUtils(); const [useWatermark, setUseWatermark] = useState(false); const [watermarkText, setWatermarkText] = useState("Lensa Saku · Kolaborasi"); const links = trpc.photo.collaborationShareLinks.useQuery({ transformId }); const refresh = () => void utils.photo.collaborationShareLinks.invalidate({ transformId });
  const create = trpc.photo.createCollaborationShareLink.useMutation({ onSuccess: async (link) => { const url = `${window.location.origin}/bagikan/${link.token}`; try { await navigator.clipboard.writeText(url); toast.success("Tautan sementara dibuat dan disalin."); } catch { toast.success("Tautan sementara dibuat. Salin dari daftar di bawah."); } refresh(); }, onError: (error) => toast.error(error.message) }); const revoke = trpc.photo.revokeCollaborationShareLink.useMutation({ onSuccess: () => { refresh(); toast.success("Tautan berbagi dicabut."); }, onError: (error) => toast.error(error.message) });
  return <div className="collaboration-share-controls"><span><Link2 size={13} /> Tautan sementara</span><label className="share-watermark-toggle"><input type="checkbox" checked={useWatermark} onChange={(event) => setUseWatermark(event.target.checked)} /><ShieldCheck size={12} /> Watermark otomatis</label>{useWatermark && <input className="share-watermark-text" value={watermarkText} maxLength={72} onChange={(event) => setWatermarkText(event.target.value)} aria-label="Teks watermark otomatis" />}<div className="share-create-buttons">{([1, 24, 72] as const).map((hours) => <button type="button" key={hours} disabled={create.isPending || (useWatermark && !watermarkText.trim())} onClick={() => create.mutate({ transformId, expiresInHours: hours, watermarkText: useWatermark ? watermarkText.trim() : undefined })}>{create.isPending ? <LoaderCircle className="spin-icon" size={12} /> : null}{hours === 1 ? "1 jam" : `${hours / 24} hari`}</button>)}</div><small>Maksimal tiga tautan aktif per hasil. Watermark diterapkan pada salinan untuk tautan ini; hasil privat asli tidak berubah.</small>{links.data?.length ? <div className="share-link-list">{links.data.map((link) => <p key={link.id}><span>{link.revokedAt ? "DICABUT" : new Date(link.expiresAt) > new Date() ? `${link.watermarkText ? "WATERMARK · " : ""}Aktif hingga ${new Date(link.expiresAt).toLocaleString("id-ID")}` : "KEDALUWARSA"}</span>{!link.revokedAt && new Date(link.expiresAt) > new Date() && <><button type="button" onClick={() => toast.message(`Tautan #${link.id} tidak dapat disalin ulang demi keamanan. Buat tautan baru bila diperlukan.`)} aria-label="Informasi tautan"><Copy size={12} /></button><button type="button" onClick={() => revoke.mutate({ shareLinkId: link.id })} aria-label="Cabut tautan"><Trash2 size={12} /></button></>}</p>)}</div> : null}</div>;
}
