import { downloadShareHistoryCsv } from "@/lib/shareHistoryCsv";
import { trpc } from "@/lib/trpc";
import { CheckSquare, FileDown, LoaderCircle, X } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";

export function CombinedShareHistoryExport({ transformIds, availableTransformIds, onSelectAll, onClearSelection }: { transformIds: number[]; availableTransformIds: number[]; onSelectAll: () => void; onClearSelection: () => void }) {
  const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const selectionTooLarge = transformIds.length > 50; const validRange = !from || !to || from <= to;
  const input = useMemo(() => ({ transformIds, from: from ? new Date(`${from}T00:00:00`) : undefined, to: to ? new Date(`${to}T23:59:59.999`) : undefined }), [from, to, transformIds]);
  const history = trpc.photo.combinedShareHistory.useQuery(input, { enabled: transformIds.length > 0 && transformIds.length <= 50 && validRange });
  const exportCsv = () => { if (!history.data?.length) return; downloadShareHistoryCsv(history.data, 0, "riwayat-berbagi-gabungan"); toast.success(`${history.data.length} aktivitas dari ${transformIds.length} frame diekspor sebagai CSV.`); };
  return <section className="combined-share-export" aria-labelledby="combined-share-export-title"><div><span className="eyebrow">EKSPOR PRIVAT / 05</span><h2 id="combined-share-export-title">Riwayat berbagi gabungan.</h2><p>Pilih satu atau lebih frame pada riwayat foto di atas, lalu unduh hanya aktivitas berbagi dari frame milikmu yang dipilih.</p></div><div className="combined-share-export-action"><div className="combined-selection-controls"><button type="button" disabled={!availableTransformIds.length || selectionTooLarge} onClick={onSelectAll}><CheckSquare size={13} /> Pilih semua yang tampil</button><button type="button" disabled={!transformIds.length} onClick={onClearSelection}><X size={13} /> Batal pilih semua</button></div><strong>{transformIds.length} frame dipilih{selectionTooLarge ? " · maksimal 50" : ""}</strong><div className="combined-date-filters"><label>Dari<input type="date" value={from} onChange={(event) => setFrom(event.target.value)} /></label><label>Sampai<input type="date" min={from || undefined} value={to} onChange={(event) => setTo(event.target.value)} /></label></div>{!validRange ? <small>Rentang tanggal belum valid.</small> : history.isLoading ? <span><LoaderCircle className="spin-icon" size={14} /> Menyiapkan riwayat…</span> : <button type="button" disabled={!history.data?.length || selectionTooLarge} onClick={exportCsv}><FileDown size={14} /> Ekspor CSV gabungan</button>}{transformIds.length > 0 && !history.isLoading && validRange && !history.data?.length && <small>Belum ada aktivitas berbagi pada frame pilihan untuk periode ini.</small>}</div></section>;
}
