import { trpc } from "@/lib/trpc";
import { Check, Pencil, Plus, RotateCcw } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

type Position = "top-left" | "top-right" | "center" | "bottom-left" | "bottom-right";
type Font = "sans" | "serif" | "mono";
const positions: { value: Position; label: string }[] = [{ value: "top-left", label: "Kiri atas" }, { value: "top-right", label: "Kanan atas" }, { value: "center", label: "Tengah" }, { value: "bottom-left", label: "Kiri bawah" }, { value: "bottom-right", label: "Kanan bawah" }];
const emptyDraft = { name: "", text: "", position: "bottom-right" as Position, size: 4, font: "sans" as Font, isActive: true };

export function GlobalBrandWatermarkPresets() {
  const utils = trpc.useUtils();
  const [draft, setDraft] = useState(emptyDraft); const [editingId, setEditingId] = useState<number | null>(null);
  const presets = trpc.admin.globalWatermarkPresets.useQuery();
  const refresh = () => { void utils.admin.globalWatermarkPresets.invalidate(); void utils.watermarkPresets.global.invalidate(); };
  const create = trpc.admin.createGlobalWatermarkPreset.useMutation({ onSuccess: () => { refresh(); setDraft(emptyDraft); toast.success("Preset brand tersedia untuk semua pengguna."); }, onError: (error) => toast.error(error.message) });
  const update = trpc.admin.updateGlobalWatermarkPreset.useMutation({ onSuccess: () => { refresh(); setDraft(emptyDraft); setEditingId(null); toast.success("Preset brand diperbarui."); }, onError: (error) => toast.error(error.message) });
  const save = () => { if (editingId) update.mutate({ id: editingId, ...draft }); else create.mutate(draft); };
  const edit = (preset: { id: number; name: string; text: string; position: Position; size: number; font: Font; isActive: boolean }) => { setEditingId(preset.id); setDraft({ name: preset.name, text: preset.text, position: preset.position, size: preset.size, font: preset.font, isActive: preset.isActive }); };
  return <section className="global-brand-watermark-manager" aria-labelledby="global-watermark-title"><header><div><span className="eyebrow">BRANDING BERSAMA</span><h2 id="global-watermark-title">Preset watermark global.</h2><p>Hanya admin dapat mengubahnya. Preset aktif tersedia di dialog berbagi semua pengguna dan hanya dipakai pada salinan hasil.</p></div><span className="global-watermark-count">{presets.data?.filter((item) => item.isActive).length ?? 0} aktif</span></header><div className="global-watermark-form"><label>Nama preset<input value={draft.name} maxLength={60} placeholder="Contoh: Tanda brand utama" onChange={(event) => setDraft((value) => ({ ...value, name: event.target.value }))} /></label><label>Teks watermark<input value={draft.text} maxLength={72} placeholder="Contoh: @lenssaku.id" onChange={(event) => setDraft((value) => ({ ...value, text: event.target.value }))} /></label><label>Posisi<select value={draft.position} onChange={(event) => setDraft((value) => ({ ...value, position: event.target.value as Position }))}>{positions.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label><label>Font<select value={draft.font} onChange={(event) => setDraft((value) => ({ ...value, font: event.target.value as Font }))}><option value="sans">Sans</option><option value="serif">Serif</option><option value="mono">Mono</option></select></label><label>Ukuran <b>{draft.size}%</b><input type="range" min="2" max="10" value={draft.size} onChange={(event) => setDraft((value) => ({ ...value, size: Number(event.target.value) }))} /></label><label className="global-watermark-active"><input type="checkbox" checked={draft.isActive} onChange={(event) => setDraft((value) => ({ ...value, isActive: event.target.checked }))} /> Aktifkan untuk pengguna</label><div className="global-watermark-actions"><button type="button" disabled={!draft.name.trim() || !draft.text.trim() || create.isPending || update.isPending} onClick={save}>{editingId ? <><Check size={14} /> Simpan perubahan</> : <><Plus size={14} /> Tambah preset global</>}</button>{editingId && <button type="button" className="global-watermark-reset" onClick={() => { setEditingId(null); setDraft(emptyDraft); }}><RotateCcw size={13} /> Batal</button>}</div></div><div className="global-watermark-list">{presets.isLoading ? <small>Memuat preset brand…</small> : presets.data?.length ? presets.data.map((preset) => <article key={preset.id} className={preset.isActive ? "is-active" : "is-inactive"}><div><span>{preset.isActive ? "TERSEDIA" : "NONAKTIF"}</span><strong>{preset.name}</strong><p>{preset.text} · {positions.find((item) => item.value === preset.position)?.label} · {preset.font} · {preset.size}%</p></div><button type="button" aria-label={`Sunting preset ${preset.name}`} onClick={() => edit(preset)}><Pencil size={14} /> Sunting</button></article>) : <small>Belum ada preset watermark global.</small>}</div></section>;
}
